apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - ingress.yaml

patches:
  - path: repo-server-dns-patch.yaml
    target:
      kind: Deployment
      name: argocd-repo-server
